name: textanalysis2
dependencies:
  - aiohttp=3.7.4.post0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - boto3=1.18.21
  - botocore=1.21.41
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2020.10.14
  - cachetools=4.2.2
  - certifi=2020.6.20
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - coverage=5.5
  - cryptography=35.0.0
  - cycler=0.11.0
  - cython=0.29.23
  - dataclasses=0.8
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - gensim=4.0.1
  - google-api-core=1.25.1
  - google-auth=1.33.0
  - google-cloud-core=1.7.1
  - google-cloud-storage=1.41.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.1
  - googleapis-common-protos=1.53.0
  - grpcio=1.36.1
  - idna=3.3
  - idna_ssl=1.1.0
  - intel-openmp=2021.4.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils
  - jedi=0.17.0
  - jinja2=3.0.2
  - jmespath=0.10.0
  - joblib=0.13.2
  - jpeg=9d
  - jsonschema=3.0.2
  - jupyter_client=7.1.0
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcrc32c=1.1.1
  - libcxx=12.0.0
  - libffi=3.3
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp-base=1.2.1
  - llvm-openmp=10.0.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - multidict=5.1.0
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - nltk=3.6.5
  - notebook=6.4.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.1.5
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.2
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.2
  - python-levenshtein=0.12.2
  - python_abi=3.6
  - pytz=2021.3
  - pyzmq=22.2.1
  - readline=8.1.2
  - regex=2021.8.3
  - requests=2.27.1
  - rsa=4.7.2
  - s3transfer=0.5.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - smart_open=5.1.0
  - sqlite=3.37.0
  - stop-words=2018.7.23
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.1.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=4.3.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wordcloud=1.8.1
  - xz=5.2.5
  - yarl=1.5.1
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - blis==0.7.5
    - catalogue==2.0.6
    - click==8.0.3
    - contextvars==2.4
    - cymem==2.0.6
    - future==0.18.2
    - geocoder==1.38.1
    - geonamescache==1.3.0
    - immutables==0.16
    - importlib-metadata==4.8.3
    - langcodes==3.3.0
    - murmurhash==1.0.6
    - pathy==0.6.1
    - preshed==3.0.6
    - pydantic==1.8.2
    - ratelim==0.1.6
    - spacy==3.2.1
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - thinc==8.0.13
    - typer==0.4.0
    - wasabi==0.9.0
    - zipp==3.6.0
